databases:
  - name: prompt-lab-prod
    databaseName: prompt_lab_prod
    user: prompt_lab
    plan: starter

services:
  - type: web
    name: prompt-lab-prod-web
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: standard
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: prompt-lab-prod
          property: connectionString
      - fromGroup: prompt-lab-prod
