databases:
  - name: prompt-lab-prod
    databaseName: prompt_lab_prod
    user: prompt_lab
    plan: starter

services:
  - type: web
    name: prompt-lab-prod-web
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: standard
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: prompt-lab-prod
          property: connectionString
      - fromGroup: prompt-lab-prod
      - key: NEXT_PUBLIC_SOCKET_URL
        value: https://prompt-lab-prod-wss.onrender.com
      # Render support says we need to manually set this because otherwise
      # sometimes it checks a different random port that NextJS opens for
      # liveness and the liveness check fails.
      - key: PORT
        value: 10000

  - type: web
    name: prompt-lab-prod-wss
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    dockerCommand: pnpm tsx src/wss-server.ts
